name       : sbsigntools
version    : 0.9.4
release    : 1
source     :
    - git|https://git.kernel.org/pub/scm/linux/kernel/git/jejb/sbsigntools.git : v0.9.4
license    : GPL-3.0-or-later
component  : system.boot
summary    : Signing utility for UEFI secure boot
description: |
    Signing utility for UEFI secure boot
builddeps  :
    - pkgconfig(libcrypto)
    - pkgconfig(uuid)
    - gnu-efi-devel
    - help2man
setup      : |
    %autogen
build      : |
    %make
install    : |
    %make_install
